doctrine:
  # Database connection configuration
  dbal:
    driver: '%env(DB_DRIVER)%'
    host: '%env(DB_HOST)%'
    port: '%env(DB_PORT)%'
    dbname: '%env(DB_NAME)%'
    user: '%env(DB_USER)%'
    password: '%env(DB_PASSWORD)%'
    charset: UTF8

  # Doctrine ORM configuration
  orm:
    auto_generate_proxy_classes: true
    proxy_namespace: App\Proxies
    proxy_dir: '%kernel.cache_dir%/doctrine/proxies'
    metadata_cache_driver: array
    query_cache_driver: array
    result_cache_driver: array
    entity_paths:
      - '%kernel.project_dir%/app/Models'
