###############################################################################
#                          Generated on .docker.io                          #
###############################################################################
version: '3.1'
services:
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        container_name: discounts_db
        volumes:
            - './discounts:/application'
        environment:
            - POSTGRES_USER=teamleader
            - POSTGRES_PASSWORD=teamleader
            - POSTGRES_DB=discounts
        ports:
            - '14004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        container_name: discounts_webserver
        volumes:
            - './discounts:/application'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: .docker/php-fpm
        working_dir: /application
        container_name: discounts_app
        volumes:
            - './discounts:/application'
